services:
  bentopdf:
    build:
      context: .
      args:
        SIMPLE_MODE: 'false'
        VITE_BRAND_NAME: 'ITERUM PDF'
    container_name: bentopdf
    restart: unless-stopped
    expose:
      - '8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
    networks:
      - coolify

networks:
  coolify:
    external: true
